# Generated by Django 4.1.2 on 2023-01-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Sub_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=45)),
                ('foil', models.BooleanField()),
                ('extended', models.BooleanField()),
                ('retro', models.BooleanField()),
                ('legendary', models.BooleanField()),
                ('quantity', models.IntegerField(default=0)),
                ('card_sub_type', models.ManyToManyField(to='mtgapp.card_sub_type')),
                ('card_type', models.ManyToManyField(to='mtgapp.card_type')),
                ('set', models.ManyToManyField(to='mtgapp.set')),
            ],
        ),
    ]
